"""Regenerates native/src/unicode_categories.h from llama.cpp's Unicode data.

The `joyai-llm` pre-tokenizer that DeepSeek-V4-Flash ships with is written in
terms of Unicode general categories (\\p{L}, \\p{M}, \\p{N}, \\p{P}, \\p{S}), so
matching the reference tokenizer means agreeing with it about which category
every codepoint is in. Deriving the table from llama.cpp's own
`src/unicode-data.cpp` -- rather than from whatever Unicode version the local
Python happens to carry -- makes that agreement exact instead of approximate.

Usage:

    python tools/generate_unicode_categories.py path/to/llama.cpp/src/unicode-data.cpp

The source file is a generated artifact in llama.cpp itself; it is parsed here
rather than vendored whole because only the category ranges and the whitespace
set are needed (the case-mapping and NFD tables are several times larger).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = Path(__file__).resolve().parents[1] / "native" / "src" / "unicode_categories.h"

RANGE_PATTERN = re.compile(r"\{\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*\}")
CODEPOINT_PATTERN = re.compile(r"0x[0-9A-Fa-f]+")


def _block(text: str, marker: str) -> str:
    start = text.index(marker)
    opening = text.index("{", start)
    depth = 0
    for at in range(opening, len(text)):
        if text[at] == "{":
            depth += 1
        elif text[at] == "}":
            depth -= 1
            if depth == 0:
                return text[opening : at + 1]
    raise ValueError(f"unterminated block for {marker}")


def main(source: str) -> int:
    text = Path(source).read_text(encoding="utf-8")

    ranges = [
        (int(start, 16), int(flags, 16))
        for start, flags in RANGE_PATTERN.findall(_block(text, "unicode_ranges_flags"))
    ]
    if not ranges or ranges[0][0] != 0:
        raise ValueError("category ranges must start at U+0000")
    ranges.sort()

    whitespace = sorted(
        {int(value, 16) for value in CODEPOINT_PATTERN.findall(_block(text, "unicode_set_whitespace"))}
    )

    out = [
        "// Generated by tools/generate_unicode_categories.py from llama.cpp's",
        "// src/unicode-data.cpp. Do not edit by hand.",
        "//",
        "// Each entry starts a range that runs until the next entry's start, so a",
        "// lookup is one upper-bound search. Flags match llama.cpp's",
        "// unicode_cpt_flags so category decisions agree with the reference",
        "// tokenizer exactly.",
        "#pragma once",
        "#include <algorithm>",
        "#include <cstdint>",
        "",
        "namespace colibri::unicode {",
        "",
        "enum Category : std::uint16_t {",
        "    kUndefined  = 0x0001,",
        "    kNumber     = 0x0002,  // \\p{N}",
        "    kLetter     = 0x0004,  // \\p{L}",
        "    kSeparator  = 0x0008,  // \\p{Z}",
        "    kAccentMark = 0x0010,  // \\p{M}",
        "    kPunctuation= 0x0020,  // \\p{P}",
        "    kSymbol     = 0x0040,  // \\p{S}",
        "    kControl    = 0x0080,  // \\p{C}",
        "};",
        "",
        "struct Range { std::uint32_t start; std::uint16_t flags; };",
        "",
        f"inline constexpr Range kRanges[] = {{  // {len(ranges)} entries",
    ]
    for start, flags in ranges:
        out.append(f"    {{0x{start:06X}, 0x{flags:04X}}},")
    out.append("};")
    out.append("")
    out.append(f"inline constexpr std::uint32_t kWhitespace[] = {{  // {len(whitespace)} entries")
    for index in range(0, len(whitespace), 8):
        chunk = ", ".join(f"0x{value:06X}" for value in whitespace[index : index + 8])
        out.append(f"    {chunk},")
    out.append("};")
    out.extend(
        [
            "",
            "inline std::uint16_t flags(std::uint32_t codepoint) {",
            "    const auto* found = std::upper_bound(",
            "        std::begin(kRanges), std::end(kRanges), codepoint,",
            "        [](std::uint32_t value, const Range& range) { return value < range.start; });",
            "    return found == std::begin(kRanges) ? kUndefined : (found - 1)->flags;",
            "}",
            "",
            "inline bool is_letter(std::uint32_t codepoint) { return (flags(codepoint) & kLetter) != 0; }",
            "inline bool is_number(std::uint32_t codepoint) { return (flags(codepoint) & kNumber) != 0; }",
            "inline bool is_accent_mark(std::uint32_t codepoint) { return (flags(codepoint) & kAccentMark) != 0; }",
            "inline bool is_punctuation(std::uint32_t codepoint) { return (flags(codepoint) & kPunctuation) != 0; }",
            "inline bool is_symbol(std::uint32_t codepoint) { return (flags(codepoint) & kSymbol) != 0; }",
            "",
            "// \\s in the reference tokenizer: the explicit whitespace set, which is",
            "// wider than the separator category (it includes the ASCII control",
            "// whitespace that \\p{Z} leaves out).",
            "inline bool is_whitespace(std::uint32_t codepoint) {",
            "    return std::binary_search(std::begin(kWhitespace), std::end(kWhitespace), codepoint);",
            "}",
            "",
            "}  // namespace colibri::unicode",
            "",
        ]
    )
    HEADER.write_text("\n".join(out), encoding="utf-8")
    print(f"{HEADER}: {len(ranges)} ranges, {len(whitespace)} whitespace codepoints")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1]))
